version: '3'
services:
  web:
    container_name: 'delifood'
    build: .
    ports:
      - '3000:3000'
    networks:
      - strapi      
      
  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
      
  apache:
    image: 'httpd:latest'
    container_name: apache
    restart: always
    ports:
      - '81:80'
    volumes:
      - ./apache/backup.conf:/usr/local/apache2/conf/httpd.conf
    links:
      - web  
      
  strapi:
    container_name: 'strapi'
    image: 'strapi/strapi:alpine'
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - mysql

  mysql:
    container_name: 'mysql'
    image: 'mysql:5.7'
    restart: unless-stopped
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - strapi
      
volumes:
  strapi-data:
  
networks:
  strapi:
    name: strapi-network
    driver: bridge